CREATE SCHEMA IF NOT EXISTS spring;

DROP TABLE IF EXISTS spring.person;

CREATE TABLE spring.person
(
    id    int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name  varchar(100) NOT NULL,
    age   int CHECK ( age > 0 AND age < 100),
    email varchar(100) NOT NULL UNIQUE
);

INSERT INTO
    spring.person(name, age, email)
VALUES
    ('Vova', 25, 'vov@mail.ru'),
    ('Tom', 32, 'tom@mail.ru'),
    ('Jerry', 41, 'jerry@yahoo.com'),
    ('Syzi', 24, 'syzi@gmail.com');

CREATE TABLE spring.item
(
    id        int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    person_id int          REFERENCES spring.person (id) ON DELETE SET NULL,
    item_name varchar(100) NOT NULL
);

INSERT INTO
    spring.item(person_id, item_name)
VALUES
    (4, 'Airpods'),
    (4, 'Playstation'),
    (1, 'TV'),
    (6, 'Iphone');

