CREATE SCHEMA IF NOT EXISTS spring;

CREATE TABLE spring.person
(
    id    int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  varchar NOT NULL,
    age   int CHECK ( age > 0 ),
    email varchar UNIQUE
);

INSERT INTO
    spring.person(name, age, email)
VALUES
    ('Tom', 23, 'tomy@mail.ru'),
    ('Andrii', 32, 'andro@mail.ru'),
    ('Mariya', 19, 'masha@yahoo.com'),
    ('Olesya', 46, 'olol@gmail.com.ru');