CREATE SCHEMA IF NOT EXISTS spring;

DROP TABLE IF EXISTS spring.person;

CREATE TABLE spring.person
(
    id         int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name  varchar(100) NOT NULL,
    birth_year int          NOT NULL CHECK ( birth_year BETWEEN 1800 AND 2023)
);

INSERT INTO
    spring.person(full_name, birth_year)
VALUES
    ('Tom Holland', 1975),
    ('Andrii Vartovsky', 1983),
    ('Mariya Sharapova', 1987),
    ('Olesya Filipenko', 1991);

DROP TABLE IF EXISTS spring.book;

CREATE TABLE spring.book
(
    id        int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title     varchar(100) NOT NULL,
    author    varchar(100) NOT NULL,
    year      int          NOT NULL CHECK ( year > 1 AND book.year < 2023),
    person_id int          REFERENCES spring.person (id) ON DELETE SET NULL,
    taken_at timestamp
);

INSERT INTO
    spring.book(title, author, year)
VALUES
    ('In Search of Lost Time', 'Marcel Proust', 2004),
    ('Ulysses ', 'James Joyce', 2014),
    ('A Portrait of the Artist as a Young Man', 'James Joyce', 2006),
    ('Finnegans', 'James Joyce', 1999),
    ('One Hundred Years of Solitude', 'Gabriel Marquez', 2013),
    ('The Great Gatsby', 'Scott Fitzgerald', 2014),
    ('Tender Is the Night', 'Scott Fitzgerald', 2012);
